import { Inter } from "next/font/google";
import "./globals.css";
import InstallBootstrap from "./components/Bootstrap/InstallBootstrap";
import "bootstrap/dist/css/bootstrap.min.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Caribe Enseña Learning",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <link rel="shortcut icon" href='/Images/Logo/Header.png' />
      </head>
      <body className={inter.className}>
        <InstallBootstrap />
        {children}
      </body>
    </html>
  );
}
